name: Build .NET Framework App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0

    - name: Restore NuGet packages
      run: nuget restore WindowsFormsApplication1.sln

    - name: Build solution
      run: msbuild WindowsFormsApplication1.sln /p:Configuration=Release /p:DeployOnBuild=true

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ArmiaPolcynCalc-artifact
        path: WindowsFormsApplication1\bin\Release\WindowsFormsApplication1.exe
